;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
((databases . (
               semmed
               orange
               robokop
               rtx
               ))

 (query-results.write-to-file?  . #t)  ;; #t will write the query and results to file, #f will not
 (query-results.file-name       . "last.sx")
 (query-results.file-name-human . "last.txt") 
 (query-results.file-name-spreadsheet . "last.tsv")
 ;; Uncomment exactly one of these:
 (query-results.file-mode       . replace)  ;; Clobber the save file each time you run a query.
 ;(query-results.file-mode       . append)  ;; Save all the queries.

 ;; Add configuration options as new association pairs.
 )
