;; DO NOT EDIT THIS FILE!
;; Instead, copy this file to config.scm and edit that.
((databases . (
               semmed
               orange
               robokop
               rtx
               ))
 ;; Add configuration options as new association pairs.
 )
