#lang racket
(provide
  (all-from-out "mk.rkt")
  (all-from-out "mk-db.rkt")

  membero
  rem-dups
  edgeo
  ~name-concepto
  DECREASES

  semmed
  monarch
  rtx
  ;scigraph
  )


(require
  "mk.rkt"
  "mk-db.rkt"
  (except-in racket/match ==))

(displayln "loading semmed")
(define semmed (time (make-db "data/semmed")))
(displayln "loading monarch-lite")
(define monarch (time (make-db "data/monarch-lite")))
(displayln "loading rtx")
(define rtx (time (make-db "data/rtx")))
;(displayln "loading scigraph")
;(define scigraph (time (make-db "data/scigraph")))

;; list membership
(define membero
  (lambda (x ls)
    (fresh (y rest)
      (== `(,y . ,rest) ls)
      (conde
        [(== x y)]
        [(=/= x y) (membero x rest)]))))

;; remove duplicates from a list
(define rem-dups
  (lambda (ls)
    (cond
      [(null? ls) '()]
      [(member (car ls) (cdr ls)) (rem-dups (cdr ls))]
      [else (cons (car ls) (rem-dups (cdr ls)))])))


(define (edgeo e)
  (conde
    ((fresh (ee) (== `(semmed . ,ee) e) (db:edgeo semmed ee)))
    ((fresh (ee) (== `(monarch . ,ee) e) (db:edgeo monarch ee)))
    ((fresh (ee) (== `(rtx . ,ee) e) (db:edgeo rtx ee)))
    ;((fresh (ee) (== `(scigraph . ,ee) e) (db:edgeo scigraph ee)))
    ))

(define (~name-concepto n c)
  (conde
    ((fresh (cc) (== `(semmed . ,cc) c) (db:~name-concepto semmed n cc)))
    ((fresh (cc) (== `(monarch . ,cc) c) (db:~name-concepto monarch n cc)))
    ((fresh (cc) (== `(rtx . ,cc) c) (db:~name-concepto rtx n cc)))
    ;((fresh (cc) (== `(scigraph . ,cc) c) (db:~name-concepto scigraph n cc)))
    ))


(define (DECREASES pred)
  (fresh (_)
    (conde
      [(== `(,_ . "treats") pred)]
      [(== `(,_ . "prevents") pred)]
      [(== `(,_ . "negatively_regulates") pred)])))

(define (INCREASES pred)
  (fresh (_)
    (conde
      [(== `(,_ . "produces") pred)]
      [(== `(,_ . "positively_regulates") pred)])))


(rem-dups
   (run* (q)
     (fresh (edge eid tacrine-details subject object pred eprops db
                  scid scui sname sdetails
                  ocid ocui oname odetails
                  pred-id pred-name)
       (== `(,eid ,subject ,object ,pred . ,eprops) edge)
       (conde
         [(~name-concepto "DNM1L" `(,db . ,object))]
         [(~name-concepto "DNM1L" `(,db . ,subject))])            
       (edgeo `(,db . ,edge))
       (== `(,pred-id . ,pred-name) pred)
       (== `(,scid ,scui ,sname . ,sdetails) subject)
       (== `(,ocid ,ocui ,oname . ,odetails) object)
       (== pred-name q))))

(sort
 (rem-dups
   (run* (q)
     (fresh (edge eid tacrine-details subject object pred eprops db
                  scid scui sname sdetails
                  ocid ocui oname odetails
                  pred-id pred-name)
       (== `(,eid ,subject ,object ,pred . ,eprops) edge)
       (~name-concepto "DNM1L" `(,db . ,object))            
       (edgeo `(,db . ,edge))     
       (== `(,pred-id . ,pred-name) pred)
       (== `(,scid ,scui ,sname . ,sdetails) subject)
       (== `(,ocid ,ocui ,oname . ,odetails) object)
       (== `(,db ,sname ,pred-name ,oname) q))))
 (lambda (e1 e2)
   (match `(,e1 ,e2)
     [`((,db1 ,sname1 ,pred-name1 ,oname1)
        (,db2 ,sname2 ,pred-name2 ,oname2))
      (string<? pred-name1 pred-name2)])))
;; =>
'((semmed "Post-Translational Protein Processing" "affects" "DNM1L wt Allele")
  (semmed "RNA Interference" "affects" "DNM1L wt Allele")
  (semmed "Signal Transduction Pathways" "affects" "DNM1L wt Allele")
  (semmed "Transcription, Genetic" "affects" "DNM1L wt Allele")
  (semmed "Glycolysis" "affects" "DNM1L wt Allele")
  (semmed "Phosphorylation" "affects" "DNM1L wt Allele")
  (semmed "Point Mutation" "affects" "DNM1L wt Allele")
  (semmed
   "GTP-Binding Protein alpha Subunit, Gq"
   "coexists_with"
   "DNM1L wt Allele")
  (semmed "CDC2 Protein Kinase" "coexists_with" "DNM1L wt Allele")
  (semmed "GNAQ wt Allele" "coexists_with" "DNM1L wt Allele")
  (semmed "AFG3L2 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "Genes" "coexists_with" "DNM1L wt Allele")
  (semmed "FIS1 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "E2F5 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "MFF gene" "coexists_with" "DNM1L wt Allele")
  (semmed "ANXA6 wt Allele" "coexists_with" "DNM1L wt Allele")
  (semmed "SPG7 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "MFN1 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "Genes, cdc" "coexists_with" "DNM1L wt Allele")
  (semmed "PPARGC1A wt Allele" "coexists_with" "DNM1L wt Allele")
  (semmed "OPA1 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "SAMM50 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "OPA3 gene" "coexists_with" "DNM1L wt Allele")
  (semmed "CCNC wt Allele" "coexists_with" "DNM1L wt Allele")
  (semmed "Homologous Gene" "coexists_with" "DNM1L wt Allele")
  (semmed "MFN2 wt Allele" "coexists_with" "DNM1L wt Allele")
  (semmed "Lysergic Acid Diethylamide" "coexists_with" "DNM1L wt Allele")
  (semmed "Methysergide" "coexists_with" "DNM1L wt Allele")
  (semmed "Calcium" "coexists_with" "DNM1L wt Allele")
  (semmed "honokiol" "coexists_with" "DNM1L wt Allele")
  (semmed
   "2-bromolysergic acid diethylamide"
   "coexists_with"
   "DNM1L wt Allele")
  (rtx "GTP" "directly_interacts_with" "DNM1L")
  (rtx "H2O" "directly_interacts_with" "DNM1L")
  (rtx "Orthophosphate" "directly_interacts_with" "DNM1L")
  (rtx "GDP" "directly_interacts_with" "DNM1L")
  (rtx "APEH" "directly_interacts_with" "DNM1L")
  (rtx "COPS5" "directly_interacts_with" "DNM1L")
  (rtx "CYHR1" "directly_interacts_with" "DNM1L")
  (rtx "ATIC" "directly_interacts_with" "DNM1L")
  (rtx "CDCA5" "directly_interacts_with" "DNM1L")
  (rtx "ATP6V1C1" "directly_interacts_with" "DNM1L")
  (rtx "PROP1" "directly_interacts_with" "DNM1L")
  (rtx "NUFIP1" "directly_interacts_with" "DNM1L")
  (rtx "UBE2H" "directly_interacts_with" "DNM1L")
  (rtx "MIEF2" "directly_interacts_with" "DNM1L")
  (rtx "FZR1" "directly_interacts_with" "DNM1L")
  (rtx "ARFIP1" "directly_interacts_with" "DNM1L")
  (rtx "CPNE2" "directly_interacts_with" "DNM1L")
  (rtx "SSB" "directly_interacts_with" "DNM1L")
  (rtx "BCL2L1" "directly_interacts_with" "DNM1L")
  (rtx "LLGL2" "directly_interacts_with" "DNM1L")
  (rtx "JMJD6" "directly_interacts_with" "DNM1L")
  (rtx "VIM" "directly_interacts_with" "DNM1L")
  (rtx "VPS26A" "directly_interacts_with" "DNM1L")
  (rtx "TES" "directly_interacts_with" "DNM1L")
  (rtx "HAX1" "directly_interacts_with" "DNM1L")
  (rtx "SAMM50" "directly_interacts_with" "DNM1L")
  (rtx "SOX2" "directly_interacts_with" "DNM1L")
  (rtx "SIRT3" "directly_interacts_with" "DNM1L")
  (rtx "NTRK1" "directly_interacts_with" "DNM1L")
  (rtx "MIEF1" "directly_interacts_with" "DNM1L")
  (rtx "TBC1D15" "directly_interacts_with" "DNM1L")
  (rtx "PPIA" "directly_interacts_with" "DNM1L")
  (rtx "PSMG3" "directly_interacts_with" "DNM1L")
  (rtx "RRM2" "directly_interacts_with" "DNM1L")
  (rtx "SCG3" "directly_interacts_with" "DNM1L")
  (rtx "DUSP23" "directly_interacts_with" "DNM1L")
  (rtx "MFF" "directly_interacts_with" "DNM1L")
  (rtx "MARCH5" "directly_interacts_with" "DNM1L")
  (rtx "PGAM5" "directly_interacts_with" "DNM1L")
  (rtx "ESR1" "directly_interacts_with" "DNM1L")
  (rtx "WDR5" "directly_interacts_with" "DNM1L")
  (rtx "SCRIB" "directly_interacts_with" "DNM1L")
  (rtx "SH3GL1" "directly_interacts_with" "DNM1L")
  (rtx "CDC5L" "directly_interacts_with" "DNM1L")
  (rtx "HSPD1" "directly_interacts_with" "DNM1L")
  (rtx "LRRK2" "directly_interacts_with" "DNM1L")
  (rtx "ZBTB24" "directly_interacts_with" "DNM1L")
  (rtx "A0A0G2JQ02" "directly_interacts_with" "DNM1L")
  (rtx "CA14" "directly_interacts_with" "DNM1L")
  (rtx "EGFR" "directly_interacts_with" "DNM1L")
  (rtx "FIS1" "directly_interacts_with" "DNM1L")
  (rtx "PINK1" "directly_interacts_with" "DNM1L")
  (rtx "TMEM11" "directly_interacts_with" "DNM1L")
  (rtx "PEX14" "directly_interacts_with" "DNM1L")
  (rtx "DGUOK" "directly_interacts_with" "DNM1L")
  (rtx "DNAAF2" "directly_interacts_with" "DNM1L")
  (rtx "GSK3B" "directly_interacts_with" "DNM1L")
  (rtx "DIABLO" "directly_interacts_with" "DNM1L")
  (rtx "MAGEA1" "directly_interacts_with" "DNM1L")
  (rtx "MAGEA3" "directly_interacts_with" "DNM1L")
  (rtx "MUL1" "directly_interacts_with" "DNM1L")
  (rtx "SNW1" "directly_interacts_with" "DNM1L")
  (rtx "MAP3K10" "directly_interacts_with" "DNM1L")
  (rtx "SEC24A" "directly_interacts_with" "DNM1L")
  (semmed "Cyclin-Dependent Kinase 5" "interacts_with" "DNM1L wt Allele")
  (semmed
   "calmodulin-dependent protein kinase II"
   "interacts_with"
   "DNM1L wt Allele")
  (semmed
   "mitogen-activated protein kinase p38"
   "interacts_with"
   "DNM1L wt Allele")
  (monarch "MFF" "interacts_with" "DNM1L")
  (semmed
   "Cyclic AMP-Dependent Protein Kinases"
   "interacts_with"
   "DNM1L wt Allele")
  (semmed "CDC2 Protein Kinase" "interacts_with" "DNM1L wt Allele")
  (monarch "DGUOK" "interacts_with" "DNM1L")
  (semmed "Ligase" "interacts_with" "DNM1L wt Allele")
  (semmed "Actins" "interacts_with" "DNM1L wt Allele")
  (monarch "CASP8" "interacts_with" "DNM1L")
  (semmed "TRANSCRIPTION FACTOR" "interacts_with" "DNM1L wt Allele")
  (semmed "Mitochondrial Proteins" "interacts_with" "DNM1L wt Allele")
  (monarch "DNM1L" "interacts_with" "DNM1L")
  (semmed "Calmodulin" "interacts_with" "DNM1L wt Allele")
  (semmed "Insulin" "interacts_with" "DNM1L wt Allele")
  (monarch "PINK1" "interacts_with" "DNM1L")
  (semmed "Specific antibody" "interacts_with" "DNM1L wt Allele")
  (semmed "PKA inhibitor" "interacts_with" "DNM1L wt Allele")
  (monarch "EGFR" "interacts_with" "DNM1L")
  (semmed "Soluble ErbB-1" "interacts_with" "DNM1L wt Allele")
  (monarch "SOD1" "interacts_with" "DNM1L")
  (semmed "TGFB1 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "SQSTM1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "SOX2" "interacts_with" "DNM1L")
  (semmed "FUNDC1 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "GSKIP gene" "interacts_with" "DNM1L wt Allele")
  (monarch "CSNK2A1" "interacts_with" "Dnm1l")
  (monarch "PEX11B" "interacts_with" "DNM1L")
  (semmed "APP gene" "interacts_with" "DNM1L wt Allele")
  (semmed "MUL1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "PEX14" "interacts_with" "DNM1L")
  (semmed "GRAP2 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "PARK7 wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "MFN2" "interacts_with" "DNM1L")
  (semmed "MIEF2 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "FIS1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "HAX1" "interacts_with" "DNM1L")
  (semmed "EGFR gene" "interacts_with" "DNM1L wt Allele")
  (semmed "CAMK2G gene" "interacts_with" "DNM1L wt Allele")
  (monarch "DNAAF2" "interacts_with" "DNM1L")
  (semmed "POLDIP2 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "NUP62 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "PRKN" "interacts_with" "DNM1L")
  (semmed "MIEF1 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "CA2 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "NTRK1" "interacts_with" "DNM1L")
  (semmed "MAPK1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "LRRK2" "interacts_with" "DNM1L")
  (semmed "MAPT gene" "interacts_with" "DNM1L wt Allele")
  (semmed "APP wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "SNW1" "interacts_with" "DNM1L")
  (semmed "AIMP2 wt Allele" "interacts_with" "DNM1L wt Allele")
  (semmed "MAPK14 wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "FIS1" "interacts_with" "DNM1L")
  (semmed "KHDRBS1 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "OPA1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "CHCHD3" "interacts_with" "DNM1L")
  (semmed "RAB32 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "CAMP gene" "interacts_with" "DNM1L wt Allele")
  (monarch "GABRR1" "interacts_with" "DNM1L")
  (semmed "RAD50 wt Allele" "interacts_with" "DNM1L wt Allele")
  (semmed "PHEX gene" "interacts_with" "DNM1L wt Allele")
  (monarch "FZR1" "interacts_with" "DNM1L")
  (semmed "SAMM50 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "AHSA1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "SAMM50" "interacts_with" "DNM1L")
  (semmed "CDK1 wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "mfn2" "interacts_with" "dnm1l")
  (semmed "CANX wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "MFN1" "interacts_with" "DNM1L")
  (semmed "MYH14 gene" "interacts_with" "DNM1L wt Allele")
  (semmed "DCTN4 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "Itsn2" "interacts_with" "Dnm1l")
  (monarch "MIEF1" "interacts_with" "DNM1L")
  (semmed "GTF2H1 wt Allele" "interacts_with" "DNM1L wt Allele")
  (semmed "EHD1 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "TBC1D15" "interacts_with" "DNM1L")
  (semmed "CRK gene" "interacts_with" "DNM1L wt Allele")
  (semmed "MFN2 wt Allele" "interacts_with" "DNM1L wt Allele")
  (monarch "MUL1" "interacts_with" "DNM1L")
  (semmed "SEPT2 gene" "interacts_with" "DNM1L wt Allele")
  (monarch "LLGL2" "interacts_with" "DNM1L")
  (semmed "Plasmids" "interacts_with" "DNM1L wt Allele")
  (semmed "arenobufagin" "interacts_with" "DNM1L wt Allele")
  (monarch "CDC5L" "interacts_with" "DNM1L")
  (semmed "Calcium" "interacts_with" "DNM1L wt Allele")
  (semmed "sodium bisulfide" "interacts_with" "DNM1L wt Allele")
  (monarch "Syngap1" "interacts_with" "Dnm1l")
  (monarch "CA14" "interacts_with" "DNM1L")
  (semmed "Staurosporine" "interacts_with" "DNM1L wt Allele")
  (semmed "15-deoxyprostaglandin J2" "interacts_with" "DNM1L wt Allele")
  (monarch "MTFP1" "interacts_with" "DNM1L")
  (semmed "Reactive Oxygen Species" "interacts_with" "DNM1L wt Allele")
  (monarch "synj1" "interacts_with" "dnm1l")
  (semmed "Cyclic AMP" "interacts_with" "DNM1L wt Allele")
  (monarch "ATP6V1C1" "interacts_with" "DNM1L")
  (monarch "Mysm1" "interacts_with" "Dnm1l")
  (monarch "MARCH5" "interacts_with" "DNM1L")
  (monarch "Eed" "interacts_with" "Dnm1l")
  (monarch "PPIA" "interacts_with" "DNM1L")
  (monarch "PEX11A" "interacts_with" "DNM1L")
  (monarch "NUFIP1" "interacts_with" "DNM1L")
  (monarch "AVL9" "interacts_with" "DNM1L")
  (monarch "Lrrk2" "interacts_with" "Dnm1l")
  (monarch "FGL1" "interacts_with" "DNM1L")
  (monarch "CDCA5" "interacts_with" "DNM1L")
  (monarch "gak" "interacts_with" "dnm1l")
  (monarch "PGAM5" "interacts_with" "DNM1L")
  (monarch "Pgam5" "interacts_with" "Dnm1l")
  (monarch "ARFIP1" "interacts_with" "DNM1L")
  (monarch "DUSP23" "interacts_with" "DNM1L")
  (monarch "COPS5" "interacts_with" "DNM1L")
  (monarch "CPNE2" "interacts_with" "DNM1L")
  (monarch "MYSM1" "interacts_with" "DNM1L")
  (monarch "Cyfip1" "interacts_with" "Dnm1l")
  (monarch "BCL2L1" "interacts_with" "DNM1L")
  (monarch "PEX11G" "interacts_with" "DNM1L")
  (monarch "synrg" "interacts_with" "dnm1l")
  (monarch "UNK" "interacts_with" "DNM1L")
  (monarch "Synj1" "interacts_with" "Dnm1l")
  (monarch "Nek2" "interacts_with" "DNM1L")
  (monarch "Akap1" "interacts_with" "Dnm1l")
  (monarch "['Kif19a', 'Kif19']" "interacts_with" "DNM1L")
  (monarch "Wdr5" "interacts_with" "DNM1L")
  (monarch "Foxp3" "interacts_with" "Dnm1l")
  (monarch "Unk" "interacts_with" "Dnm1l")
  (monarch "eps15" "interacts_with" "dnm1l")
  (monarch "Ppp3r1" "interacts_with" "Dnm1l")
  (monarch "casp8" "interacts_with" "dnm1l")
  (monarch "LOC100911485" "interacts_with" "Dnm1l")
  (monarch "grapa" "interacts_with" "dnm1l")
  (monarch "Grb2" "interacts_with" "Dnm1l")
  (monarch "mfn1b" "interacts_with" "dnm1l")
  (monarch "Exoc5" "interacts_with" "Dnm1l")
  (monarch "itsn2a" "interacts_with" "dnm1l")
  (monarch "Casp8" "interacts_with" "Dnm1l")
  (monarch "grb2b" "interacts_with" "dnm1l")
  (monarch "Sept7" "interacts_with" "Dnm1l")
  (monarch "grb2a" "interacts_with" "dnm1l")
  (monarch "Mfn1" "interacts_with" "Dnm1l")
  (monarch "eps15l1a" "interacts_with" "dnm1l")
  (monarch "Eps15l1" "interacts_with" "Dnm1l")
  (monarch "grapb" "interacts_with" "dnm1l")
  (monarch "Eps15" "interacts_with" "Dnm1l")
  (monarch "itsn2b" "interacts_with" "dnm1l")
  (monarch "Mfn2" "interacts_with" "Dnm1l")
  (monarch "itsn1" "interacts_with" "dnm1l")
  (monarch "Trip12" "interacts_with" "Dnm1l")
  (monarch "Fis1" "interacts_with" "Dnm1l")
  (monarch #f "interacts_with" "dnm1l")
  (semmed "Entire hippocampus" "location_of" "DNM1L wt Allele")
  (semmed "Retina" "location_of" "DNM1L wt Allele")
  (semmed "Tissue membrane" "location_of" "DNM1L wt Allele")
  (semmed "Muscle" "location_of" "DNM1L wt Allele")
  (semmed "Heart" "location_of" "DNM1L wt Allele")
  (semmed "Neostriatum" "location_of" "DNM1L wt Allele")
  (semmed "Brain" "location_of" "DNM1L wt Allele")
  (semmed "Ovary" "location_of" "DNM1L wt Allele")
  (semmed "Body tissue" "location_of" "DNM1L wt Allele")
  (semmed "Cerebral cortex" "location_of" "DNM1L wt Allele")
  (semmed "Common carotid artery" "location_of" "DNM1L wt Allele")
  (semmed "Kidney" "location_of" "DNM1L wt Allele")
  (semmed "HeLa Cells" "location_of" "DNM1L wt Allele")
  (semmed "Hepatocyte" "location_of" "DNM1L wt Allele")
  (semmed "Differentiated muscle cell" "location_of" "DNM1L wt Allele")
  (semmed "Mammalian Cell" "location_of" "DNM1L wt Allele")
  (semmed "Neurons" "location_of" "DNM1L wt Allele")
  (semmed "Lymphocyte" "location_of" "DNM1L wt Allele")
  (semmed "Primary spermatocyte" "location_of" "DNM1L wt Allele")
  (semmed "Cells" "location_of" "DNM1L wt Allele")
  (semmed "Peripheral Blood Lymphocyte" "location_of" "DNM1L wt Allele")
  (semmed "Chinese Hamster Ovary Cell" "location_of" "DNM1L wt Allele")
  (semmed "Cultured Cells" "location_of" "DNM1L wt Allele")
  (semmed "Oocytes" "location_of" "DNM1L wt Allele")
  (semmed "Fibroblasts" "location_of" "DNM1L wt Allele")
  (semmed "Neuroglia" "location_of" "DNM1L wt Allele")
  (semmed "Adipocytes" "location_of" "DNM1L wt Allele")
  (semmed "Clone Cells" "location_of" "DNM1L wt Allele")
  (semmed "Purkinje Cells" "location_of" "DNM1L wt Allele")
  (semmed "trans-Golgi Network" "location_of" "DNM1L wt Allele")
  (semmed "Golgi Apparatus" "location_of" "DNM1L wt Allele")
  (semmed "Mitochondria" "location_of" "DNM1L wt Allele")
  (semmed "Mitochondrial Membrane, Outer" "location_of" "DNM1L wt Allele")
  (semmed "Dendritic Spines" "location_of" "DNM1L wt Allele")
  (semmed "Organelles" "location_of" "DNM1L wt Allele")
  (semmed "Membrane" "location_of" "DNM1L wt Allele")
  (semmed "cell cortex" "location_of" "DNM1L wt Allele")
  (semmed "Cytoplasm" "location_of" "DNM1L wt Allele")
  (semmed "Chromosomes, Human, Pair 21" "location_of" "DNM1L wt Allele")
  (semmed "Cell Fraction" "location_of" "DNM1L wt Allele")
  (semmed "Endoplasmic Reticulum" "location_of" "DNM1L wt Allele")
  (semmed "Mitochondrial Membranes" "location_of" "DNM1L wt Allele")
  (semmed
   "Mitochondrial electron transport chain"
   "location_of"
   "DNM1L wt Allele")
  (semmed
   "mitogen-activated protein kinase p38"
   "negatively_regulates"
   "DNM1L wt Allele")
  (semmed "Citrate (si)-Synthase" "negatively_regulates" "DNM1L wt Allele")
  (semmed
   "Cyclic AMP-Dependent Protein Kinases"
   "negatively_regulates"
   "DNM1L wt Allele")
  (semmed "angiogenin" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PRDX3 peroxidase" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Mitochondrial Proteins" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Collagen Type I" "negatively_regulates" "DNM1L wt Allele")
  (semmed "alpha-Synuclein" "negatively_regulates" "DNM1L wt Allele")
  (semmed "SIRT4 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "SQSTM1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "GRAP2 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MIEF2 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "HTRA2 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ACSM3 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "GPAM gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MFF gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ANXA6 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PKM2 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "CS gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PRKAB1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "POLDIP2 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "TP53 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "TP53 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MIEF1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MAPK1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "S100A7 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "AIMP2 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MAPK14 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ERVK-15 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "CUX1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ANG gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PRDX3 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PRKAA2 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "SART3 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PRKAA1 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "AHSA1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "PINK1 gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "CRK gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "SIX1 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Homologous Gene" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MFN2 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ROS1 wt Allele" "negatively_regulates" "DNM1L wt Allele")
  (semmed
   "Carbonyl Cyanide m-Chlorophenyl Hydrazone"
   "negatively_regulates"
   "DNM1L wt Allele")
  (semmed "Bicuculline" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Niclosamide" "negatively_regulates" "DNM1L wt Allele")
  (semmed "MicroRNAs" "negatively_regulates" "DNM1L wt Allele")
  (semmed "15-deoxyprostaglandin J2" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Reactive Oxygen Species" "negatively_regulates" "DNM1L wt Allele")
  (semmed "ginkgolide K" "negatively_regulates" "DNM1L wt Allele")
  (semmed
   "9-deoxy-delta-9-prostaglandin D2"
   "negatively_regulates"
   "DNM1L wt Allele")
  (semmed "Small Molecule" "negatively_regulates" "DNM1L wt Allele")
  (semmed "cryptolepine" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Ru 360" "negatively_regulates" "DNM1L wt Allele")
  (semmed "RNA, Small Interfering" "negatively_regulates" "DNM1L wt Allele")
  (semmed "Lithium Chloride" "negatively_regulates" "DNM1L wt Allele")
  (semmed "E-Cadherin" "part_of" "DNM1L wt Allele")
  (semmed "ezrin" "part_of" "DNM1L wt Allele")
  (semmed "Cytoplasmic Protein" "part_of" "DNM1L wt Allele")
  (semmed "alpha-Synuclein" "part_of" "DNM1L wt Allele")
  (semmed "Regulatory Sequences, Nucleic Acid" "part_of" "DNM1L wt Allele")
  (semmed "RNA, Small Interfering" "part_of" "DNM1L wt Allele")
  (semmed "Cyclin-Dependent Kinase 5" "positively_regulates" "DNM1L wt Allele")
  (semmed
   "Proto-Oncogene Proteins c-akt"
   "positively_regulates"
   "DNM1L wt Allele")
  (semmed "Calcineurin" "positively_regulates" "DNM1L wt Allele")
  (semmed "Mitochondrial Proteins" "positively_regulates" "DNM1L wt Allele")
  (semmed
   "Receptor Protein-Tyrosine Kinases"
   "positively_regulates"
   "DNM1L wt Allele")
  (semmed
   "mitochondrial calcium uniporter"
   "positively_regulates"
   "DNM1L wt Allele")
  (semmed "SQSTM1 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "BAX wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed "E2F5 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "ATG5 wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed "AKT1 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "FAS gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "BAK1 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "OPA1 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "PRKAA2 wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed "MAP1LC3A gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "BECN1 wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed "BAX gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "ROCK1 gene" "positively_regulates" "DNM1L wt Allele")
  (semmed "MFN2 wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed "ROS1 wt Allele" "positively_regulates" "DNM1L wt Allele")
  (semmed
   "Lysergic Acid Diethylamide Tartrate"
   "positively_regulates"
   "DNM1L wt Allele")
  (semmed "Reactive Oxygen Species" "positively_regulates" "DNM1L wt Allele")
  (semmed "Cadmium" "positively_regulates" "DNM1L wt Allele")
  (semmed "Ceramides" "positively_regulates" "DNM1L wt Allele")
  (semmed "Hydrogen Peroxide" "positively_regulates" "DNM1L wt Allele")
  (semmed "Cells" "produces" "DNM1L protein, human")
  (semmed "Phosphotransferases" "produces" "DNM1L wt Allele")
  (semmed "CATALASE" "produces" "DNM1L wt Allele")
  (semmed "Mitochondrial Proteins" "produces" "DNM1L wt Allele")
  (semmed "SOD2 gene" "produces" "DNM1L wt Allele")
  (semmed "MFN1 gene" "produces" "DNM1L wt Allele")
  (semmed "CAT gene" "produces" "DNM1L wt Allele")
  (semmed "OPA1 gene" "produces" "DNM1L wt Allele")
  (semmed "PINK1 gene" "produces" "DNM1L wt Allele")
  (semmed "MFN2 wt Allele" "produces" "DNM1L wt Allele")
  (semmed "Neurons" "produces" "DNM1L wt Allele")
  (semmed "Cells" "produces" "DNM1L wt Allele")
  (semmed "Oocytes" "produces" "DNM1L wt Allele")
  (semmed "Podocytes" "produces" "DNM1L wt Allele")
  (semmed "Myocytes, Cardiac" "produces" "DNM1L wt Allele")
  (semmed "Mitochondria" "produces" "DNM1L wt Allele")
  (rtx "TFAP2A" "regulates" "DNM1L")
  (rtx "TBP" "regulates" "DNM1L")
  (rtx "RCOR1" "regulates" "DNM1L")
  (rtx "CHD7" "regulates" "DNM1L")
  (rtx "ELK1" "regulates" "DNM1L")
  (rtx "EOMES" "regulates" "DNM1L")
  (rtx "IRF3" "regulates" "DNM1L")
  (rtx "JUND" "regulates" "DNM1L")
  (rtx "MAPK3" "regulates" "DNM1L")
  (rtx "MAZ" "regulates" "DNM1L")
  (rtx "ZNF143" "regulates" "DNM1L")
  (rtx "HNF4A" "regulates" "DNM1L")
  (rtx "ZC3H11A" "regulates" "DNM1L")
  (rtx "CTCF" "regulates" "DNM1L")
  (rtx "E2F4" "regulates" "DNM1L")
  (rtx "E2F1" "regulates" "DNM1L")
  (rtx "JUN" "regulates" "DNM1L")
  (rtx "KDM4A" "regulates" "DNM1L")
  (rtx "KDM5B" "regulates" "DNM1L")
  (rtx "GTF2F1" "regulates" "DNM1L")
  (rtx "CDX2" "regulates" "DNM1L")
  (rtx "STAT1" "regulates" "DNM1L")
  (rtx "KLF4" "regulates" "DNM1L")
  (rtx "CEBPB" "regulates" "DNM1L")
  (rtx "HMGN3" "regulates" "DNM1L")
  (rtx "POU5F1" "regulates" "DNM1L")
  (rtx "ZNF384" "regulates" "DNM1L")
  (rtx "NFYA" "regulates" "DNM1L")
  (rtx "SMARCB1" "regulates" "DNM1L")
  (rtx "ZMIZ1" "regulates" "DNM1L")
  (rtx "IRF1" "regulates" "DNM1L")
  (rtx "SMC3" "regulates" "DNM1L")
  (rtx "MAPK1" "regulates" "DNM1L")
  (rtx "SMARCC1" "regulates" "DNM1L")
  (rtx "TBL1XR1" "regulates" "DNM1L")
  (rtx "SPI1" "regulates" "DNM1L")
  (rtx "BRD7" "regulates" "DNM1L")
  (rtx "TAL1" "regulates" "DNM1L")
  (rtx "SP1" "regulates" "DNM1L")
  (rtx "HDAC1" "regulates" "DNM1L")
  (rtx "CHD1" "regulates" "DNM1L")
  (rtx "SMARCC2" "regulates" "DNM1L")
  (rtx "GATA3" "regulates" "DNM1L")
  (rtx "HDAC2" "regulates" "DNM1L")
  (rtx "EP300" "regulates" "DNM1L")
  (rtx "SETDB1" "regulates" "DNM1L")
  (rtx "MGEA5" "regulates" "DNM1L")
  (rtx "PPARG" "regulates" "DNM1L")
  (rtx "MXI1" "regulates" "DNM1L")
  (rtx "NRF1" "regulates" "DNM1L")
  (rtx "PRKCD" "regulates" "DNM1L")
  (rtx "ZNF274" "regulates" "DNM1L")
  (rtx "NFATC1" "regulates" "DNM1L")
  (rtx "MAFK" "regulates" "DNM1L")
  (rtx "USF2" "regulates" "DNM1L")
  (rtx "RBBP5" "regulates" "DNM1L")
  (rtx "RFX5" "regulates" "DNM1L")
  (rtx "TRIM28" "regulates" "DNM1L")
  (rtx "BRCA1" "regulates" "DNM1L")
  (rtx "SIRT6" "regulates" "DNM1L")
  (rtx "SMARCA4" "regulates" "DNM1L")
  (rtx "SAP30" "regulates" "DNM1L")
  (rtx "RAD21" "regulates" "DNM1L")
  (rtx "ZNF263" "regulates" "DNM1L")
  (rtx "MAX" "regulates" "DNM1L")
  (rtx "ETV1" "regulates" "DNM1L")
  (rtx "EZH2" "regulates" "DNM1L")
  (rtx "KDM5A" "regulates" "DNM1L")
  (rtx "CDK1" "regulates" "DNM1L")
  (rtx "UBTF" "regulates" "DNM1L")
  (rtx "CUX1" "regulates" "DNM1L")
  (rtx "PINK1" "regulates" "DNM1L")
  (rtx "GATA2" "regulates" "DNM1L")
  (rtx "BACH1" "regulates" "DNM1L")
  (rtx "PHF8" "regulates" "DNM1L")
  (rtx "CDK5" "regulates" "DNM1L")
  (rtx "PRKACA" "regulates" "DNM1L")
  (rtx "CHD2" "regulates" "DNM1L")
  (rtx "MYC" "regulates" "DNM1L")
  (rtx "SREBF1" "regulates" "DNM1L")
  (rtx "STAT3" "regulates" "DNM1L")
  (rtx "SUZ12" "regulates" "DNM1L")
  (rtx "INS" "regulates" "DNM1L")
  (rtx "E2F6" "regulates" "DNM1L")
  (rtx "FOXA1" "regulates" "DNM1L")
  (rtx "GSK3B" "regulates" "DNM1L")
  (rtx "WRNIP1" "regulates" "DNM1L")
  (rtx "BCL6" "regulates" "DNM1L")
  (rtx "BHLHE40" "regulates" "DNM1L")
  (rtx "ESRRA" "regulates" "DNM1L")
  (rtx "ETS1" "regulates" "DNM1L")
  (rtx "GATA1" "regulates" "DNM1L")
  (rtx "HCFC1" "regulates" "DNM1L")
  (rtx "CCNT2" "regulates" "DNM1L")
  (rtx "CDK2" "regulates" "DNM1L")
  (rtx "MIR3183" "regulates" "DNM1L")
  (rtx "MIR371B" "regulates" "DNM1L")
  (rtx "MIR3132" "regulates" "DNM1L")
  (rtx "MIR516A1" "regulates" "DNM1L")
  (rtx "MIR711" "regulates" "DNM1L")
  (rtx "MIR365A" "regulates" "DNM1L")
  (rtx "MIR4723" "regulates" "DNM1L")
  (rtx "MIR4687" "regulates" "DNM1L")
  (rtx "MIR197" "regulates" "DNM1L")
  (rtx "MIR4782" "regulates" "DNM1L")
  (rtx "MIR513C" "regulates" "DNM1L")
  (rtx "MIR5001" "regulates" "DNM1L")
  (rtx "MIR4633" "regulates" "DNM1L")
  (rtx "MIR5706" "regulates" "DNM1L")
  (rtx "MIR502" "regulates" "DNM1L")
  (rtx "MIR516A2" "regulates" "DNM1L"))

'((scigraph
   "GTP-Binding Protein alpha Subunit, Gq"
   "coexists_with"
   "DNM1L gene")
  (scigraph "CDC2 Protein Kinase" "coexists_with" "DNM1L gene")
  (scigraph "XRCC1 protein, human" "coexists_with" "DNM1L gene")
  (scigraph "porin" "coexists_with" "DNM1L gene")
  (scigraph "arenobufagin" "coexists_with" "DNM1L gene")
  (scigraph "Lysergic Acid Diethylamide" "coexists_with" "DNM1L gene")
  (scigraph "Cardiolipins" "coexists_with" "DNM1L gene")
  (scigraph "Staurosporine" "coexists_with" "DNM1L gene")
  (scigraph "Glucose" "coexists_with" "DNM1L gene")
  (scigraph "Calcium" "coexists_with" "DNM1L gene")
  (scigraph "MFN1 gene" "coexists_with" "DNM1L gene")
  (scigraph "FIS1 gene" "coexists_with" "DNM1L gene")
  (scigraph "SAMM50 gene" "coexists_with" "DNM1L gene")
  (scigraph "CCNC gene" "coexists_with" "DNM1L gene")
  (scigraph "Genes, cdc" "coexists_with" "DNM1L gene")
  (scigraph "Genes" "coexists_with" "DNM1L gene")
  (scigraph "Homologous Gene" "coexists_with" "DNM1L gene")
  (scigraph "MFN2 gene" "coexists_with" "DNM1L gene")
  (scigraph "cyclin C" "coexists_with" "DNM1L gene")
  (scigraph "GNAQ gene" "coexists_with" "DNM1L gene")
  (scigraph "ANXA6 gene" "coexists_with" "DNM1L gene")
  (scigraph "MFF" "interacts_with" "DNM1L")
  (scigraph "DGUOK" "interacts_with" "DNM1L")
  (scigraph "CASP8" "interacts_with" "DNM1L")
  (scigraph "CSNK2A1" "interacts_with" "Dnm1l")
  (scigraph "DNM1L" "interacts_with" "DNM1L")
  (scigraph "PINK1" "interacts_with" "DNM1L")
  (scigraph "EGFR" "interacts_with" "DNM1L")
  (scigraph "SOD1" "interacts_with" "DNM1L")
  (scigraph "SOX2" "interacts_with" "DNM1L")
  (scigraph "mfn2" "interacts_with" "dnm1l")
  (scigraph "PEX11B" "interacts_with" "DNM1L")
  (scigraph "PEX14" "interacts_with" "DNM1L")
  (scigraph "MFN2" "interacts_with" "DNM1L")
  (scigraph "HAX1" "interacts_with" "DNM1L")
  (scigraph "synj1" "interacts_with" "dnm1l")
  (scigraph "DNAAF2" "interacts_with" "DNM1L")
  (scigraph "Syngap1" "interacts_with" "Dnm1l")
  (scigraph "PRKN" "interacts_with" "DNM1L")
  (scigraph "NTRK1" "interacts_with" "DNM1L")
  (scigraph "Eed" "interacts_with" "Dnm1l")
  (scigraph "LRRK2" "interacts_with" "DNM1L")
  (scigraph "gak" "interacts_with" "dnm1l")
  (scigraph "SNW1" "interacts_with" "DNM1L")
  (scigraph "Lrrk2" "interacts_with" "Dnm1l")
  (scigraph "Itsn2" "interacts_with" "Dnm1l")
  (scigraph "FIS1" "interacts_with" "DNM1L")
  (scigraph "CHCHD3" "interacts_with" "DNM1L")
  (scigraph "MUL1 gene" "interacts_with" "DNM1L gene")
  (scigraph "GABRR1" "interacts_with" "DNM1L")
  (scigraph "synrg" "interacts_with" "dnm1l")
  (scigraph "FZR1" "interacts_with" "DNM1L")
  (scigraph "Cyfip1" "interacts_with" "Dnm1l")
  (scigraph "SAMM50" "interacts_with" "DNM1L")
  (scigraph "MFN1" "interacts_with" "DNM1L")
  (scigraph "Akap1" "interacts_with" "Dnm1l")
  (scigraph "MIEF1" "interacts_with" "DNM1L")
  (scigraph "eps15" "interacts_with" "dnm1l")
  (scigraph "TBC1D15" "interacts_with" "DNM1L")
  (scigraph "Foxp3" "interacts_with" "Dnm1l")
  (scigraph "Mysm1" "interacts_with" "Dnm1l")
  (scigraph "Unk" "interacts_with" "Dnm1l")
  (scigraph "MUL1" "interacts_with" "DNM1L")
  (scigraph "MIEF2 gene" "interacts_with" "DNM1L gene")
  (scigraph "LLGL2" "interacts_with" "DNM1L")
  (scigraph "casp8" "interacts_with" "dnm1l")
  (scigraph "CDC5L" "interacts_with" "DNM1L")
  (scigraph "CA14" "interacts_with" "DNM1L")
  (scigraph "grapa" "interacts_with" "dnm1l")
  (scigraph "Pgam5" "interacts_with" "Dnm1l")
  (scigraph "MTFP1" "interacts_with" "DNM1L")
  (scigraph "FIS1 gene" "interacts_with" "DNM1L gene")
  (scigraph "ATP6V1C1" "interacts_with" "DNM1L")
  (scigraph "mfn1b" "interacts_with" "dnm1l")
  (scigraph "MARCH5" "interacts_with" "DNM1L")
  (scigraph "PPIA" "interacts_with" "DNM1L")
  (scigraph "itsn2a" "interacts_with" "dnm1l")
  (scigraph "Synj1" "interacts_with" "Dnm1l")
  (scigraph "PEX11A" "interacts_with" "DNM1L")
  (scigraph "MYH14 gene" "interacts_with" "DNM1L gene")
  (scigraph "NUFIP1" "interacts_with" "DNM1L")
  (scigraph "grb2b" "interacts_with" "dnm1l")
  (scigraph "AVL9" "interacts_with" "DNM1L")
  (scigraph "FGL1" "interacts_with" "DNM1L")
  (scigraph "grb2a" "interacts_with" "dnm1l")
  (scigraph "Ppp3r1" "interacts_with" "Dnm1l")
  (scigraph "CDCA5" "interacts_with" "DNM1L")
  (scigraph "SAMM50 gene" "interacts_with" "DNM1L gene")
  (scigraph "PGAM5" "interacts_with" "DNM1L")
  (scigraph "eps15l1a" "interacts_with" "dnm1l")
  (scigraph "ARFIP1" "interacts_with" "DNM1L")
  (scigraph "DUSP23" "interacts_with" "DNM1L")
  (scigraph "grapb" "interacts_with" "dnm1l")
  (scigraph "LOC100911485" "interacts_with" "Dnm1l")
  (scigraph "COPS5" "interacts_with" "DNM1L")
  (scigraph "FUNDC1 gene" "interacts_with" "DNM1L gene")
  (scigraph "CPNE2" "interacts_with" "DNM1L")
  (scigraph "itsn2b" "interacts_with" "dnm1l")
  (scigraph "MYSM1" "interacts_with" "DNM1L")
  (scigraph "BCL2L1" "interacts_with" "DNM1L")
  (scigraph "itsn1" "interacts_with" "dnm1l")
  (scigraph "Grb2" "interacts_with" "Dnm1l")
  (scigraph "PEX11G" "interacts_with" "DNM1L")
  (scigraph "OPA1 gene" "interacts_with" "DNM1L gene")
  (scigraph "UNK" "interacts_with" "DNM1L")
  (scigraph #f "interacts_with" "dnm1l")
  (scigraph "Nek2" "interacts_with" "DNM1L")
  (scigraph "Exoc5" "interacts_with" "Dnm1l")
  (scigraph "['Kif19a', 'Kif19']" "interacts_with" "DNM1L")
  (scigraph "MAPT gene" "interacts_with" "DNM1L gene")
  (scigraph "Wdr5" "interacts_with" "DNM1L")
  (scigraph "Casp8" "interacts_with" "Dnm1l")
  (scigraph "MIEF1 gene" "interacts_with" "DNM1L gene")
  (scigraph "Sept7" "interacts_with" "Dnm1l")
  (scigraph "PARK7 gene" "interacts_with" "DNM1L gene")
  (scigraph "Mfn1" "interacts_with" "Dnm1l")
  (scigraph "MFN2 gene" "interacts_with" "DNM1L gene")
  (scigraph "Eps15l1" "interacts_with" "Dnm1l")
  (scigraph "MAPK1 gene" "interacts_with" "DNM1L gene")
  (scigraph "Eps15" "interacts_with" "Dnm1l")
  (scigraph "NIN gene" "interacts_with" "DNM1L gene")
  (scigraph "Mfn2" "interacts_with" "Dnm1l")
  (scigraph "CDK1 gene" "interacts_with" "DNM1L gene")
  (scigraph "Trip12" "interacts_with" "Dnm1l")
  (scigraph "MFF gene" "interacts_with" "DNM1L gene")
  (scigraph "Fis1" "interacts_with" "Dnm1l")
  (scigraph "CAMP gene" "interacts_with" "DNM1L gene")
  (scigraph "RAD50 gene" "interacts_with" "DNM1L gene")
  (scigraph "CANX gene" "interacts_with" "DNM1L gene")
  (scigraph "TGFB1 gene" "interacts_with" "DNM1L gene")
  (scigraph "RAB32 gene" "interacts_with" "DNM1L gene")
  (scigraph "CAMK2G gene" "interacts_with" "DNM1L gene")
  (scigraph "CA2 gene" "interacts_with" "DNM1L gene")
  (scigraph "PHEX gene" "interacts_with" "DNM1L gene")
  (scigraph "SEPT2 gene" "interacts_with" "DNM1L gene")
  (scigraph "Purkinje Cells" "location_of" "DNM1L gene")
  (scigraph "trans-Golgi Network" "location_of" "DNM1L gene")
  (scigraph "Dendritic Spines" "location_of" "DNM1L gene")
  (scigraph "Peripheral Blood Lymphocyte" "location_of" "DNM1L gene")
  (scigraph "Chinese Hamster Ovary Cell" "location_of" "DNM1L gene")
  (scigraph "Mitochondrial Membrane, Outer" "location_of" "DNM1L gene")
  (scigraph "Differentiated muscle cell" "location_of" "DNM1L gene")
  (scigraph "perinuclear region" "location_of" "DNM1L gene")
  (scigraph "Primary spermatocyte" "location_of" "DNM1L gene")
  (scigraph "Cytosol" "location_of" "DNM1L gene")
  (scigraph "Golgi Apparatus" "location_of" "DNM1L gene")
  (scigraph "Cytoplasm" "location_of" "DNM1L gene")
  (scigraph "Mitochondrial Membranes" "location_of" "DNM1L gene")
  (scigraph "Mammalian Cell" "location_of" "DNM1L gene")
  (scigraph "Tissue membrane" "location_of" "DNM1L gene")
  (scigraph "Clone Cells" "location_of" "DNM1L gene")
  (scigraph "Neostriatum" "location_of" "DNM1L gene")
  (scigraph "Endoplasmic Reticulum" "location_of" "DNM1L gene")
  (scigraph "Entire substantia nigra" "location_of" "DNM1L gene")
  (scigraph "Lymphocyte" "location_of" "DNM1L gene")
  (scigraph "Cultured Cells" "location_of" "DNM1L gene")
  (scigraph "Common carotid artery" "location_of" "DNM1L gene")
  (scigraph "Hela Cells" "location_of" "DNM1L gene")
  (scigraph "Cell Fraction" "location_of" "DNM1L gene")
  (scigraph "Neuroglia" "location_of" "DNM1L gene")
  (scigraph "cell cortex" "location_of" "DNM1L gene")
  (scigraph "Fibroblasts" "location_of" "DNM1L gene")
  (scigraph "Mitochondria" "location_of" "DNM1L gene")
  (scigraph "Muscle" "location_of" "DNM1L gene")
  (scigraph "Retina" "location_of" "DNM1L gene")
  (scigraph "Heart" "location_of" "DNM1L gene")
  (scigraph "Cells" "location_of" "DNM1L gene")
  (scigraph "Organelles" "location_of" "DNM1L gene")
  (scigraph "Brain" "location_of" "DNM1L gene")
  (scigraph "Kidney" "location_of" "DNM1L gene")
  (scigraph "Oocytes" "location_of" "DNM1L gene")
  (scigraph "Adipocytes" "location_of" "DNM1L gene")
  (scigraph "Entire hippocampus" "location_of" "DNM1L gene")
  (scigraph "Chromosomes, Human, Pair 12" "location_of" "DNM1L gene")
  (scigraph "Membrane" "location_of" "DNM1L gene")
  (scigraph "Neurons" "location_of" "DNM1L gene")
  (scigraph "alpha-Synuclein" "negatively_regulates" "DNM1L gene")
  (scigraph "Chaperonin 10" "negatively_regulates" "DNM1L gene")
  (scigraph "PRDX3 peroxidase" "negatively_regulates" "DNM1L gene")
  (scigraph
   "Cyclic AMP-Dependent Protein Kinases"
   "negatively_regulates"
   "DNM1L gene")
  (scigraph "Citrate (si)-Synthase" "negatively_regulates" "DNM1L gene")
  (scigraph "Mitochondrial Proteins" "negatively_regulates" "DNM1L gene")
  (scigraph
   "Guanosine Triphosphate Phosphohydrolases"
   "negatively_regulates"
   "DNM1L gene")
  (scigraph "angiogenin" "negatively_regulates" "DNM1L gene")
  (scigraph
   "9-deoxy-delta-9-prostaglandin D2"
   "negatively_regulates"
   "DNM1L gene")
  (scigraph "Ru 360" "negatively_regulates" "DNM1L gene")
  (scigraph "15-deoxyprostaglandin J2" "negatively_regulates" "DNM1L gene")
  (scigraph "Bicuculline" "negatively_regulates" "DNM1L gene")
  (scigraph
   "Carbonyl Cyanide m-Chlorophenyl Hydrazone"
   "negatively_regulates"
   "DNM1L gene")
  (scigraph "Niclosamide" "negatively_regulates" "DNM1L gene")
  (scigraph "Reactive Oxygen Species" "negatively_regulates" "DNM1L gene")
  (scigraph "Lithium Chloride" "negatively_regulates" "DNM1L gene")
  (scigraph "small molecule" "negatively_regulates" "DNM1L gene")
  (scigraph "RNA, Small Interfering" "negatively_regulates" "DNM1L gene")
  (scigraph "MIEF2 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "GPAM gene" "negatively_regulates" "DNM1L gene")
  (scigraph "SIRT4 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "PKM gene" "negatively_regulates" "DNM1L gene")
  (scigraph "MIEF1 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "CUX1 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "S100A7 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "ANG gene" "negatively_regulates" "DNM1L gene")
  (scigraph "Homologous Gene" "negatively_regulates" "DNM1L gene")
  (scigraph "MFN2 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "MFF gene" "negatively_regulates" "DNM1L gene")
  (scigraph "PRDX3 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "ROS1 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "PINK1 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "SART3 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "HTRA2 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "ERVK-15 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "CS gene" "negatively_regulates" "DNM1L gene")
  (scigraph "ANXA6 gene" "negatively_regulates" "DNM1L gene")
  (scigraph "E-Cadherin" "part_of" "DNM1L gene")
  (scigraph "ezrin" "part_of" "DNM1L gene")
  (scigraph "Ubiquitin" "part_of" "DNM1L gene")
  (scigraph "RNA, Small Interfering" "part_of" "DNM1L gene")
  (scigraph "Guanosine Triphosphate" "part_of" "DNM1L gene")
  (scigraph "Regulatory Sequences, Nucleic Acid" "part_of" "DNM1L gene")
  (scigraph "BECN1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "ROCK1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "MAP1LC3A gene" "positively_regulates" "DNM1L gene")
  (scigraph "OPA1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "AKT1 gene" "positively_regulates" "DNM1L gene")
  (scigraph
   "tumor necrosis factor alpha receptor"
   "positively_regulates"
   "DNM1L gene")
  (scigraph "SQSTM1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "FAS gene" "positively_regulates" "DNM1L gene")
  (scigraph "ROS1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "BAK1 gene" "positively_regulates" "DNM1L gene")
  (scigraph "BAX gene" "positively_regulates" "DNM1L gene")
  (scigraph "ATG5 gene" "positively_regulates" "DNM1L gene")
  (scigraph "Myocytes, Cardiac" "produces" "DNM1L gene")
  (scigraph "Mitochondria" "produces" "DNM1L gene")
  (scigraph "Cells" "produces" "DNM1L gene")
  (scigraph "Oocytes" "produces" "DNM1L gene")
  (scigraph "Neurons" "produces" "DNM1L gene")
  (scigraph "Phosphotransferases" "produces" "DNM1L gene")
  (scigraph "CATALASE" "produces" "DNM1L gene")
  (scigraph "CAT gene" "produces" "DNM1L gene")
  (scigraph "PINK1 gene" "produces" "DNM1L gene")
  (scigraph "SOD2 gene" "produces" "DNM1L gene"))


#|
(semmed "SQSTM1 gene" "positively_regulates" "DNM1L wt Allele")

(run* (q)
  (fresh (edge eid tacrine-details subject object pred eprops db
               scid scui sname sdetails
               ocid ocui oname odetails
               pred-id pred-name)
    (== `(,eid ,subject ,object ,pred . ,eprops) edge)
    (~name-concepto "DNM1L" `(,db . ,object))            
    (edgeo `(,db . ,edge))     
    (== `(,pred-id . ,pred-name) pred)
    (== `(,scid ,scui ,sname . ,sdetails) subject)
    (== `(,ocid ,ocui ,oname . ,odetails) object)
    (== "SQSTM1 gene" sname)
    (== "positively_regulates" pred-name)
    (== `(,db . ,edge) q)))

(sort
 (rem-dups
   (run* (q)
     (fresh (edge eid tacrine-details subject object pred eprops db
                  scid scui sname sdetails
                  ocid ocui oname odetails
                  pred-id pred-name)
       (== `(,eid ,subject ,object ,pred . ,eprops) edge)
       (~name-concepto "DNM1L" `(,db . ,object))            
       (edgeo `(,db . ,edge))     
       (== `(,pred-id . ,pred-name) pred)
       (== `(,scid ,scui ,sname . ,sdetails) subject)
       (== `(,ocid ,ocui ,oname . ,odetails) object)
       (== `(,db ,sname ,pred-name ,oname) q))))
 (lambda (e1 e2)
   (match `(,e1 ,e2)
     [`((,db1 ,sname1 ,pred-name1 ,oname1)
        (,db2 ,sname2 ,pred-name2 ,oname2))
      (string<? pred-name1 pred-name2)])))

(rem-dups
   (run* (q)
     (fresh (edge eid tacrine-details subject object pred eprops db
                  scid scui sname sdetails
                  ocid ocui oname odetails
                  pred-id pred-name)
       (== `(,eid ,subject ,object ,pred . ,eprops) edge)
       (~name-concepto "DNM1L" `(,db . ,object))            
       (edgeo `(,db . ,edge))     
       (== `(,pred-id . ,pred-name) pred)
       (== `(,scid ,scui ,sname . ,sdetails) subject)
       (== `(,ocid ,ocui ,oname . ,odetails) object)
       (== `(,db ,sname ,pred-name ,oname) q))))

(displayln "preds for X ANY-PRED DNM1L")
(time (rem-dups
        (run* (q)
            (fresh (edge eid tacrine-details subject object pred eprops db)
              (== `(,eid ,subject ,object ,pred . ,eprops) edge)
              (~name-concepto "DNM1L" `(,db . ,object))            
              (edgeo `(,db . ,edge))
              (== pred q)))))

(displayln "preds for DNM1L ANY-PRED X")
(time (rem-dups
        (run* (q)
            (fresh (edge eid tacrine-details subject object pred eprops db)
              (== `(,eid ,subject ,object ,pred . ,eprops) edge)
              (~name-concepto "DNM1L" `(,db . ,subject))
              (edgeo `(,db . ,edge))
              (== pred q)))))

;; count the number of edges
(time (length
       (rem-dups
        (run* (q)
          (fresh (edge eid tacrine-details subject object pred eprops db)
            (== `(,eid ,subject ,object ,pred . ,eprops) edge)
            (~name-concepto "DNM1L" `(,db . ,object))            
            (edgeo `(,db . ,edge))
            (== `(,db . ,edge) q))))))
|#

#|
(displayln "X ANY-PRED DNM1L")
(time (pretty-print
       (run* (q)
         (fresh (edge name db)
           (fresh (subject scid scui sname sdetails
                           object ocid ocui oname odetails
                           eid pid pred eprops)
             (== `(,scid ,scui ,sname . ,sdetails) subject)
             (== `(,ocid ,ocui ,oname . ,odetails) object)
             (== `(,eid ,subject ,object (,pid . ,pred) . ,eprops) edge)
             (~name-concepto "DNM1L" `(,db . ,object))
             (== `(,sname ,pred ,oname) q)
             (edgeo `(,db . ,edge)))))))
|#

(newline)
(displayln "X INCREASES DNM1L:")
(time (pretty-print
        (run* (edge)
          (fresh (eid tacrine-details subject object pred eprops db)
            (== `(,eid ,subject ,object ,pred . ,eprops) edge)
            (~name-concepto "DNM1L" `(,db . ,object))
            (INCREASES pred)
            (edgeo `(,db . ,edge))))))
