;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
(
 (buffer-size                . 100000)
 (progress-logging-threshold . 1000000)
 ;; interactive, always, never
 (update-policy              . interactive)
 (cleanup-policy             . interactive)
 (migrate-policy             . interactive)
 (allow-missing-data-policy  . always)
 ;; biased-interleaving (default), depth-first
 (search-strategy            . #f)

 ;; Specify installed databases as a list of symbols, e.g.:
 ;;   (databases                  . (rtx2-20210204))
 ;;
 ;; Unless more specifically configured, we assume no databases have been installed:
 (databases                  . ())

 ;; Disable this flag to prevent translator-web-server.rkt
 ;; and open-api/ from making downstream HTTP requests.  Useful
 ;; for functional CI tests, and for offline development.
 (trapi-enable-external-requests?  . #t)

 ;; Add new configuration options as new association pairs.
 )
