;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
(
 (buffer-size                . 100000)
 (progress-logging-threshold . 1000000)
 ;; interactive, always, never
 (update-policy              . interactive)
 (cleanup-policy             . interactive)
 (migrate-policy             . interactive)
 (allow-missing-data-policy  . interactive)
 ;; biased-interleaving (default), depth-first
 (search-strategy            . #f)

 (databases                  . (semmed rtx2-20210204))
 ;; Add configuration options as new association pairs.
 )
