;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
(
 ;; Add configuration options as new association pairs.
 (relation-root-path         . "data")
 (buffer-size                . 100000)
 (progress-logging-threshold . 1000000)
 (update-policy              . interactive)
 (cleanup-policy             . interactive)
 (migrate-policy             . interactive)
 )
